testthat::test_that("the R workflow completes and resumes on explicitly synthetic donors", {
  withr::local_dir(PROJECT_ROOT); directory <- withr::local_tempdir(); study <- make_synthetic_study(directory)
  first <- run_pipeline(study$config_path)
  testthat::expect_true(all(first$stages$status == "executed"))
  final_path <- object_path(study$config, "annotate"); before <- file_sha256(final_path)
  second <- run_pipeline(study$config_path)
  testthat::expect_true(all(second$stages$status == "cached"))
  testthat::expect_identical(before, file_sha256(final_path))
  object <- readRDS(final_path); input <- readRDS(object_path(study$config, "ingest"))
  testthat::expect_equal(Matrix::nnzero(raw_counts(object) - raw_counts(input)[rownames(object), colnames(object), drop = FALSE]), 0)
  testthat::expect_true(all(is.finite(SeuratObject::Embeddings(object, "umap"))))
  testthat::expect_true(file.exists(file.path(study$config$output_dir, "report.html")))
})
testthat::test_that("Harmony runs using configured metadata on synthetic captures", {
  withr::local_dir(PROJECT_ROOT); directory <- withr::local_tempdir(); study <- make_synthetic_study(directory)
  study$config$embedding$integration <- "harmony"; study$write_config(study$config, study$config_path)
  run_pipeline(study$config_path, until = "reduce")
  object <- readRDS(object_path(study$config, "reduce"))
  testthat::expect_true("harmony" %in% names(object@reductions))
  testthat::expect_true(all(is.finite(SeuratObject::Embeddings(object, "harmony"))))
})
testthat::test_that("DESeq2 recovers a known synthetic donor-level effect", {
  withr::local_dir(PROJECT_ROOT); directory <- withr::local_tempdir(); study <- make_synthetic_study(directory)
  stage_ingest(study$config); object <- readRDS(object_path(study$config, "ingest"))
  object$cell_type <- unname(study$known_types[colnames(object)]); object$annotation_status <- "reviewed"
  path <- file.path(directory, "reviewed.rds"); saveRDS(object, path)
  output <- file.path(directory, "de")
  result <- pseudobulk_de(path, output, "T cells", "case", "control", min_cells = 20)
  effects <- result$log2FoldChange[result$gene %in% sprintf("GENE%03d", 1:6)]
  testthat::expect_length(effects, 6L)
  testthat::expect_true(all(is.finite(effects) & effects > 1))
  pb <- readRDS(file.path(output, "pseudobulk_counts.rds"))
  testthat::expect_equal(ncol(pb$counts), 6L)
  testthat::expect_true(all(pb$metadata$n_cells == 48L))
})
