html_escape <- function(x) {
  x <- gsub("&", "&amp;", as.character(x), fixed = TRUE)
  x <- gsub("<", "&lt;", x, fixed = TRUE); x <- gsub(">", "&gt;", x, fixed = TRUE)
  gsub('"', "&quot;", x, fixed = TRUE)
}
html_table <- function(x, max_rows = 100) {
  x <- head(x, max_rows)
  if (!nrow(x)) return("<p>No rows in this table.</p>")
  cells <- apply(x, 1, function(row) paste0("<tr><td>", paste(html_escape(row), collapse = "</td><td>"), "</td></tr>"))
  paste0("<div class='scroll'><table><thead><tr><th>", paste(html_escape(names(x)), collapse = "</th><th>"),
    "</th></tr></thead><tbody>", paste(cells, collapse = ""), "</tbody></table></div>")
}
stage_report <- function(cfg) {
  root <- cfg$output_dir; object <- readRDS(object_path(cfg, "annotate"))
  audit <- utils::read.csv(file.path(root, "tables/cell_qc.csv"))
  summary <- list(implementation = "R / Seurat", input_cells = nrow(audit), retained_cells = ncol(object),
    retained_genes = nrow(object), clusters = length(unique(object$cluster)),
    predicted_doublets_before_final_qc = sum(audit$doublet_class == "doublet"),
    final_counts_total_umi = sum(raw_counts(object)), doublet_detection = cfg$doublets$enabled,
    integration = cfg$embedding$integration, annotation_status = unique(object$annotation_status),
    python_runtime_initialized = if (requireNamespace("reticulate", quietly = TRUE)) reticulate::py_available(initialize = FALSE) else FALSE)
  versions <- data.frame(package = required_packages(), version = vapply(required_packages(), function(x) as.character(utils::packageVersion(x)), character(1)))
  read_table <- function(name) utils::read.csv(file.path(root, "tables", name), check.names = FALSE)
  figures <- c("qc.png", "doublets.png", "variable_genes.png", "pca_elbow.png", "umap_clusters.png",
    "marker_dotplot.png", "feature_markers.png", "umap_celltypes.png", "enrichment.png")
  images <- vapply(figures, function(name) paste0("<figure><img alt='", html_escape(name),
    "' src='", base64enc::dataURI(file = file.path(root, "figures", name), mime = "image/png"), "'><figcaption>",
    html_escape(name), "</figcaption></figure>"), character(1))
  intro <- if (cfg$input$mode == "demo") "10x Genomics PBMC3k: a cell-called count matrix from one healthy donor." else
    "User-supplied count matrices. Input identifiers, checksums and capture metadata are recorded in provenance/inputs.json."
  html <- paste0("<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>",
    "<title>scRNA-seq R analysis report</title><style>body{font:16px/1.6 system-ui,sans-serif;color:#18334a;background:#f4f7fa;margin:0}",
    "main{max-width:1160px;margin:0 auto;padding:32px}h1,h2{color:#123b56}section{background:white;padding:24px;margin:20px 0;border-radius:10px}",
    "img{width:100%;height:auto}figure{margin:24px 0}figcaption{color:#526777;font-size:13px}.scroll{overflow:auto}",
    "table{border-collapse:collapse;width:100%;font-size:14px}td,th{padding:8px;text-align:left;border-bottom:1px solid #dce5ec}",
    "th{background:#edf4f8}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:13px}</style></head><body><main>",
    "<h1>scRNA-seq learning: R / Seurat</h1><p>", html_escape(intro), "</p><section><h2>Observed results</h2>",
    html_table(data.frame(metric = names(summary)[1:8], value = vapply(summary[1:8], as.character, character(1)))),
    "<p>All displayed results were generated by the R workflow. Candidate labels require manual marker review.</p></section>",
    "<section><h2>Quality control by capture</h2>", html_table(read_table("qc_summary.csv")),
    "<p>The cell audit records every input cell and every removal reason. scDblFinder operates per physical capture after a minimum-gene screen; final QC follows doublet calling.</p></section>",
    "<section><h2>Figures and annotation evidence</h2>", paste(images, collapse = "\n"),
    html_table(read_table("annotation_evidence.csv")), "<h2>Cell label counts</h2>", html_table(read_table("celltype_counts.csv")), "</section>",
    "<section><h2>Top cluster markers</h2>", html_table(read_table("markers_top10.csv")),
    "<p>Wilcoxon tests compare each cluster with the other cells. Seurat uses Bonferroni-adjusted marker p-values. These are exploratory cluster markers, not donor-level disease tests.</p></section>",
    "<section><h2>Methods and interpretation</h2><p>RNA counts are retained. LogNormalize and VST precede variable-gene scaling, PCA, graph neighbors, Louvain clustering and R-native uwot UMAP.</p>",
    "<p>Automatic labels use a documented marker-panel heuristic, not a probability. NKG7 and PRF1 alone do not distinguish NK from cytotoxic T cells. Review CD3D, CD3E and TRAC alongside GNLY and KLRD1.</p>",
    "<p>Reactome over-representation uses each cluster's tested-gene universe and BH correction across every eligible pathway, including zero-overlap pathways.</p>",
    "<p>The one-donor PBMC3k demo cannot support a disease/control comparison. Donor-level DESeq2 is a separate extension requiring independent donors and reviewed labels. FASTQ alignment, empty-droplet calling and full ambient-RNA estimation are outside this executed count-matrix demo.</p></section>",
    "<section><h2>Configuration</h2><pre>", html_escape(paste(capture.output(dput(cfg)), collapse = "\n")), "</pre><h2>R package versions</h2>", html_table(versions),
    "<p>PBMC3k data: 10x Genomics, CC BY 4.0. Reactome data: CC0; Reactome_2022 snapshot distributed by Enrichr. See resources for source URLs and SHA-256 checksums.</p></section></main></body></html>")
  writeLines(html, file.path(root, "report.html"), useBytes = TRUE)
  writeLines(capture.output(utils::sessionInfo()), file.path(root, "provenance/sessionInfo.txt"))
  c(file.path(root, "report.html"), file.path(root, "provenance/sessionInfo.txt"),
    write_json(summary, file.path(root, "run_summary.json")), write_csv(versions, file.path(root, "provenance/package_versions.csv")))
}
